import 'package:dart_programing/app/views/enum/side_menu_enum.dart';
import 'package:dart_programing/app/views/side_menu/side_menu_controller.dart';
import 'package:dart_programing/modules/home/controllers/app_bar_controller.dart';
import 'package:dart_programing/modules/interview_prep/models/interview_question.dart';
import 'package:dart_programing/utils/constants/strings/string_keys.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class DartQAController extends GetxController {
  bool showBackToTopButton = false;
  late ScrollController scrollController;

  var selectedLevel = Rx<QuestionLevel?>(null);
  var expandedIndex = RxInt(-1);
  var visibleCount = RxInt(10);

  List<InterviewQuestion> allQuestions = [
    InterviewQuestion(id: 'd1', question: 'What is Dart and what are its key features?', answer: 'Dart is a client-optimized, object-oriented, class-based language developed by Google. Key features: strongly typed with type inference, null safety, AOT and JIT compilation, async/await built-in, rich standard library, garbage collected, and cross-platform (mobile, web, desktop, server).', level: QuestionLevel.beginner, category: 'Basics'),
    InterviewQuestion(id: 'd2', question: 'What is the difference between var, final, and const in Dart?', answer: 'var: infers type at compile time, value can change. final: value is set once at runtime and cannot be reassigned. const: compile-time constant, deeply immutable. Example: var x = 5; x = 10; // ok. final y = DateTime.now(); // ok. const z = 42; // ok, const pi = 3.14;', codeExample: 'var name = "Alice";  // mutable\nfinal age = 30;      // immutable after assignment\nconst pi = 3.14159; // compile-time constant', level: QuestionLevel.beginner, category: 'Variables'),
    InterviewQuestion(id: 'd3', question: 'What is null safety in Dart and how does it work?', answer: 'Null safety means variables cannot be null unless explicitly declared nullable with ?. Non-nullable types: int, String, List. Nullable types: int?, String?, List?. The late keyword defers initialization. The ! operator asserts non-null (throws if null). Null-aware operators: ?., ??, ??=', codeExample: 'String name = "Alice";     // non-nullable\nString? nickname;           // nullable\nnickname ??= "Ali";         // assign if null\nString upper = nickname!.toUpperCase(); // assert non-null\nint length = nickname?.length ?? 0;    // safe access', level: QuestionLevel.beginner, category: 'Null Safety'),
    InterviewQuestion(id: 'd4', question: 'Explain async, await, and Future in Dart.', answer: 'Future represents a value that will be available in the future (like a Promise in JS). async marks a function as asynchronous and makes it return a Future. await pauses execution until the Future completes. Use try/catch for error handling with async/await.', codeExample: 'Future<String> fetchData() async {\n  await Future.delayed(Duration(seconds: 2));\n  return "Hello, World!";\n}\n\nvoid main() async {\n  try {\n    final result = await fetchData();\n    print(result);\n  } catch (e) {\n    print("Error: \$e");\n  }\n}', level: QuestionLevel.beginner, category: 'Async'),
    InterviewQuestion(id: 'd5', question: 'What are Streams in Dart?', answer: 'A Stream is a sequence of asynchronous events over time. Single-subscription streams can only be listened to once. Broadcast streams can have multiple listeners. Use StreamController to create custom streams. StreamBuilder in Flutter listens to streams reactively.', codeExample: '// Single stream\nStream<int> countTo5() async* {\n  for (int i = 1; i <= 5; i++) {\n    await Future.delayed(Duration(seconds: 1));\n    yield i;\n  }\n}\n\n// Listen\ncountTo5().listen((value) => print(value));\n\n// Broadcast stream\nfinal controller = StreamController<int>.broadcast();\ncontroller.stream.listen((v) => print("A: \$v"));\ncontroller.stream.listen((v) => print("B: \$v"));\ncontroller.add(42);', level: QuestionLevel.intermediate, category: 'Async'),
    InterviewQuestion(id: 'd6', question: 'What are Isolates in Dart?', answer: 'Isolates are Dart\'s concurrency model. Each isolate has its own memory heap and event loop — no shared memory. Communication happens via message passing (SendPort/ReceivePort). Use compute() in Flutter for simple background tasks. Dart 3 introduced Isolate.run() for even simpler background execution.', codeExample: 'import "dart:isolate";\n\nvoid heavyTask(SendPort sendPort) {\n  int result = 0;\n  for (int i = 0; i < 1000000; i++) result += i;\n  sendPort.send(result);\n}\n\nvoid main() async {\n  final receivePort = ReceivePort();\n  await Isolate.spawn(heavyTask, receivePort.sendPort);\n  final result = await receivePort.first;\n  print("Result: \$result");\n}', level: QuestionLevel.advanced, category: 'Concurrency'),
    InterviewQuestion(id: 'd7', question: 'What is the difference between abstract classes and interfaces in Dart?', answer: 'Dart does not have a separate interface keyword. Every class can be used as an interface using "implements". Abstract classes use the "abstract" keyword and can have method implementations. You can implement multiple interfaces but extend only one class. Use abstract for base classes with shared behavior, interfaces for capability contracts.', codeExample: 'abstract class Animal {\n  String name;\n  Animal(this.name);\n  void breathe() => print("Breathing");\n  void speak(); // abstract method\n}\n\nclass Dog extends Animal {\n  Dog(super.name);\n  @override\n  void speak() => print("Woof!");\n}\n\n// Interface usage\nclass Flyable {\n  void fly() {}\n}\nclass Bird extends Animal implements Flyable {\n  Bird(super.name);\n  @override\n  void speak() => print("Tweet!");\n  @override\n  void fly() => print("Flap!");\n}', level: QuestionLevel.intermediate, category: 'OOP'),
    InterviewQuestion(id: 'd8', question: 'What are mixins in Dart?', answer: 'Mixins allow reusing code in multiple class hierarchies without inheritance. Use "mixin" keyword to define, "with" to apply. Mixins cannot be instantiated and cannot have constructors. They can define methods and variables. Use "on" to restrict which classes can use a mixin.', codeExample: 'mixin Logger {\n  void log(String message) => print("[LOG] \$message");\n}\n\nmixin Validator {\n  bool isValidEmail(String email) =>\n      RegExp(r"^[\\w-.]+@[\\w-]+\\.[a-z]{2,4}\$").hasMatch(email);\n}\n\nclass UserService with Logger, Validator {\n  void createUser(String email) {\n    if (isValidEmail(email)) {\n      log("Creating user: \$email");\n    } else {\n      log("Invalid email: \$email");\n    }\n  }\n}', level: QuestionLevel.intermediate, category: 'OOP'),
    InterviewQuestion(id: 'd9', question: 'What are extension methods in Dart?', answer: 'Extension methods add functionality to existing types without modifying them or creating subclasses. Defined with "extension Name on Type". Can add methods, getters, setters, and operators. Useful for adding utility methods to third-party types.', codeExample: 'extension StringExtensions on String {\n  String capitalize() {\n    if (isEmpty) return this;\n    return "\${this[0].toUpperCase()}\${substring(1).toLowerCase()}";\n  }\n\n  bool get isValidEmail =>\n      RegExp(r"^[\\w-.]+@[\\w-]+\\.[a-z]{2,4}\$").hasMatch(this);\n\n  List<String> get words => trim().split(RegExp(r"\\s+"));\n}\n\nvoid main() {\n  print("hello world".capitalize()); // Hello world\n  print("test@gmail.com".isValidEmail); // true\n  print("  hello  world  ".words); // [hello, world]\n}', level: QuestionLevel.intermediate, category: 'Extensions'),
    InterviewQuestion(id: 'd10', question: 'What are generics in Dart?', answer: 'Generics allow writing reusable code that works with different types while maintaining type safety. Use <T> for type parameters. Common in collections (List<T>, Map<K,V>), Futures (Future<T>), and custom classes.', codeExample: '// Generic class\nclass Pair<A, B> {\n  final A first;\n  final B second;\n  Pair(this.first, this.second);\n\n  @override\n  String toString() => "(\$first, \$second)";\n}\n\n// Generic function\nT getFirst<T>(List<T> list) => list.first;\n\n// Bounded generics\nclass SortedList<T extends Comparable<T>> {\n  final List<T> _items = [];\n  void add(T item) {\n    _items.add(item);\n    _items.sort();\n  }\n}\n\nvoid main() {\n  final pair = Pair<String, int>("age", 25);\n  print(pair); // (age, 25)\n  print(getFirst([1, 2, 3])); // 1\n}', level: QuestionLevel.intermediate, category: 'Generics'),
    InterviewQuestion(id: 'd11', question: 'What are factory constructors in Dart?', answer: 'Factory constructors return an instance of the class (or subtype) without necessarily creating a new object each time. Used for: singleton pattern, returning a cached instance, returning a subtype, and complex initialization logic.', codeExample: 'class Logger {\n  static final Logger _instance = Logger._internal();\n  factory Logger() => _instance; // singleton\n  Logger._internal();\n  void log(String msg) => print("[LOG] \$msg");\n}\n\n// Named factory with subtype return\nclass Shape {\n  factory Shape.create(String type) {\n    switch (type) {\n      case "circle": return Circle();\n      case "square": return Square();\n      default: throw ArgumentError("Unknown shape: \$type");\n    }\n  }\n}\nclass Circle extends Shape {}\nclass Square extends Shape {}', level: QuestionLevel.intermediate, category: 'Constructors'),
    InterviewQuestion(id: 'd12', question: 'What is cascade notation (..) in Dart?', answer: 'Cascade notation allows performing multiple operations on the same object without repeating the object reference. Two dots (..) for objects, three dots (...) for null-safe cascade. Useful for builder-pattern style code.', codeExample: '// Without cascade\nfinal paint1 = Paint();\npaint1.color = Colors.red;\npaint1.strokeWidth = 2.0;\npaint1.style = PaintingStyle.stroke;\n\n// With cascade\nfinal paint2 = Paint()\n  ..color = Colors.red\n  ..strokeWidth = 2.0\n  ..style = PaintingStyle.stroke;\n\n// Null-safe cascade\nString? text;\ntext?..replaceAll(" ", ""); // no-op if null\n\n// Method chaining style\nfinal buffer = StringBuffer()\n  ..write("Hello, ")\n  ..write("World")\n  ..writeln("!");\nprint(buffer.toString());', level: QuestionLevel.beginner, category: 'Syntax'),
    InterviewQuestion(id: 'd13', question: 'What are Records in Dart 3?', answer: 'Records are anonymous, immutable, aggregate types added in Dart 3. They allow bundling multiple values together without creating a class. Use positional or named fields. Useful for returning multiple values from functions.', codeExample: '// Named fields\n(String name, int age) getUser() => (name: "Alice", age: 30);\n\n// Positional fields\n(int, String) getIndexed() => (0, "zero");\n\nvoid main() {\n  final user = getUser();\n  print(user.name); // Alice\n  print(user.age);  // 30\n\n  final indexed = getIndexed();\n  print(indexed.\$1); // 0 (positional access)\n  print(indexed.\$2); // zero\n\n  // Destructuring\n  final (name: n, age: a) = getUser();\n  print("\$n is \$a years old");\n\n  // In switch\n  switch (user) {\n    case (name: "Alice", age: _): print("Found Alice!");\n  }\n}', level: QuestionLevel.advanced, category: 'Dart 3'),
    InterviewQuestion(id: 'd14', question: 'What are sealed classes in Dart 3?', answer: 'Sealed classes (Dart 3) restrict which classes can extend or implement them to the same library. When used in a switch, the compiler verifies all subtypes are handled (exhaustive switch). Great for modeling sum types / discriminated unions.', codeExample: 'sealed class Result<T> {}\n\nclass Success<T> extends Result<T> {\n  final T data;\n  Success(this.data);\n}\n\nclass Failure<T> extends Result<T> {\n  final String error;\n  Failure(this.error);\n}\n\n// Exhaustive switch — compiler ensures all cases handled\nString handleResult(Result<String> result) => switch (result) {\n  Success(data: final d) => "Success: \$d",\n  Failure(error: final e) => "Error: \$e",\n};\n\nvoid main() {\n  print(handleResult(Success("Hello")));\n  print(handleResult(Failure("Network error")));\n}', level: QuestionLevel.advanced, category: 'Dart 3'),
    InterviewQuestion(id: 'd15', question: 'What is the late keyword in Dart?', answer: 'The late keyword defers initialization of a non-nullable variable. The variable must be assigned before it is read, or a LateInitializationError is thrown at runtime. Useful for: dependency injection, heavy initialization, circular references, and top-level variables.', codeExample: 'class UserService {\n  late final DatabaseService _db;\n  late String _cachedData;\n\n  void initialize(DatabaseService db) {\n    _db = db; // assigned exactly once (final)\n  }\n\n  String getData() {\n    // _cachedData is computed lazily on first access\n    if (!_isCached) {\n      _cachedData = _db.fetch();\n    }\n    return _cachedData;\n  }\n}\n\n// Late with initializer — computed lazily on first access\nlate final String config = loadConfig();\nString loadConfig() => "loaded"; // only called when config is first accessed', level: QuestionLevel.intermediate, category: 'Null Safety'),
    InterviewQuestion(id: 'd16', question: 'What are the different types of functions in Dart?', answer: 'Dart supports: regular functions (named), anonymous functions (lambda), arrow functions (=>), higher-order functions (take/return functions), closures (capture outer scope), and recursive functions. Functions are first-class objects in Dart.', codeExample: '// Named function\nint add(int a, int b) => a + b;\n\n// Anonymous function\nvar multiply = (int a, int b) => a * b;\n\n// Higher-order function\nList<T> map<T, R>(List<R> list, T Function(R) fn) =>\n    list.map(fn).toList();\n\n// Closure — captures outer variable\nFunction makeCounter() {\n  int count = 0;\n  return () => ++count;\n}\nfinal counter = makeCounter();\nprint(counter()); // 1\nprint(counter()); // 2\n\n// Optional and named parameters\nvoid greet(String name, {String? title, int age = 0}) {\n  print("Hello, \${title != null ? "\$title " : ""}\$name! Age: \$age");\n}\ngreet("Alice", title: "Dr.", age: 30);', level: QuestionLevel.beginner, category: 'Functions'),
    InterviewQuestion(id: 'd17', question: 'What is the difference between == and identical() in Dart?', answer: '== compares by value (can be overridden). identical() checks if two references point to the same object in memory. For small integers and string literals, Dart may intern them (identical returns true). For custom classes, override == and hashCode together.', codeExample: 'class Point {\n  final int x, y;\n  const Point(this.x, this.y);\n\n  @override\n  bool operator ==(Object other) =>\n      other is Point && other.x == x && other.y == y;\n\n  @override\n  int get hashCode => Object.hash(x, y);\n}\n\nvoid main() {\n  final p1 = Point(1, 2);\n  final p2 = Point(1, 2);\n  print(p1 == p2);        // true (value equality)\n  print(identical(p1, p2)); // false (different objects)\n\n  const p3 = Point(1, 2);\n  const p4 = Point(1, 2);\n  print(identical(p3, p4)); // true (const canonicalization)\n}', level: QuestionLevel.intermediate, category: 'Operators'),
    InterviewQuestion(id: 'd18', question: 'What are Dart patterns (pattern matching)?', answer: 'Dart 3 introduced patterns for destructuring and matching. Types: literal patterns, variable patterns, wildcard (_), logical patterns (&&, ||), record patterns, list patterns, map patterns, object patterns, and null-check/assert patterns. Used in switch, if-case, and destructuring assignments.', codeExample: '// Switch expression with patterns\nString describe(Object obj) => switch (obj) {\n  int i when i < 0 => "negative int",\n  int i when i == 0 => "zero",\n  int _ => "positive int",\n  String s when s.isEmpty => "empty string",\n  String s => "string: \$s",\n  [var first, ..., var last] => "list from \$first to \$last",\n  _ => "something else",\n};\n\n// if-case\nvoid processShape(Shape shape) {\n  if (shape case Circle(radius: var r)) {\n    print("Circle with radius \$r");\n  }\n}', level: QuestionLevel.advanced, category: 'Dart 3'),
    InterviewQuestion(id: 'd19', question: 'What is type promotion in Dart null safety?', answer: 'Type promotion automatically narrows the type of a variable after a null or type check. If you check "if (x != null)", inside that block x is promoted to non-nullable. Similarly, "if (x is String)" promotes x to String within the block. Promotion does not work for class fields (use local variables instead).', codeExample: 'void process(String? text) {\n  if (text == null) return;\n  // text is now promoted to String (non-nullable)\n  print(text.length); // no ! needed\n}\n\nvoid describe(Object value) {\n  if (value is int) {\n    print(value.isEven); // value promoted to int\n  } else if (value is String) {\n    print(value.toUpperCase()); // value promoted to String\n  }\n}\n\n// Note: promotion does NOT work for class fields\nclass Foo {\n  String? name;\n  void demo() {\n    if (name != null) {\n      // name might be set to null by another thread\n      // final localName = name; // use local variable\n      print(name!.length); // must use !\n    }\n  }\n}', level: QuestionLevel.intermediate, category: 'Null Safety'),
    InterviewQuestion(id: 'd20', question: 'What is the difference between List, Set, and Map in Dart?', answer: 'List: ordered collection with duplicates, indexed access O(1), search O(n). Set: unordered collection without duplicates, contains() is O(1). Map: key-value pairs, unique keys, lookup by key O(1). Choose List for ordered sequences, Set for unique values, Map for key-based lookup.', codeExample: '// List\nfinal list = [1, 2, 2, 3];\nprint(list[0]); // 1\nlist.add(4);\n\n// Set\nfinal set = {1, 2, 2, 3};\nprint(set); // {1, 2, 3} — no duplicates\nprint(set.contains(2)); // true — O(1)\n\n// Map\nfinal map = {"name": "Alice", "age": 30};\nprint(map["name"]); // Alice\nmap["city"] = "NYC";\nmap.forEach((k, v) => print("\$k: \$v"));\n\n// where/map/reduce\nfinal evens = [1,2,3,4,5].where((n) => n.isEven).toList(); // [2, 4]\nfinal doubled = [1,2,3].map((n) => n * 2).toList(); // [2, 4, 6]\nfinal sum = [1,2,3,4,5].reduce((a, b) => a + b); // 15', level: QuestionLevel.beginner, category: 'Collections'),
    InterviewQuestion(id: 'd21', question: 'What is the Spread operator (...) in Dart?', answer: 'The spread operator (...) inserts all elements of a collection into another. Null-aware spread (...?) handles null collections. Works with List, Set, and Map literals.', codeExample: 'final list1 = [1, 2, 3];\nfinal list2 = [4, 5, 6];\nfinal combined = [...list1, ...list2]; // [1,2,3,4,5,6]\n\nList<int>? nullableList;\nfinal safe = [0, ...?nullableList, 7]; // [0, 7]\n\n// Spread in Map\nfinal defaults = {"color": "blue", "size": "medium"};\nfinal custom = {"size": "large", ...defaults};\n// Note: later keys overwrite earlier ones', level: QuestionLevel.beginner, category: 'Syntax'),
    InterviewQuestion(id: 'd22', question: 'What are enums in Dart and what enhanced features do they have?', answer: 'Dart supports basic enums (enum Day { mon, tue }) and enhanced enums (Dart 2.17+) that can have fields, constructors, and methods. Enhanced enums can implement interfaces and mix in mixins.', codeExample: 'enum Planet {\n  mercury(3.37e23, 2.44e6),\n  earth(5.97e24, 6.37e6),\n  mars(6.42e23, 3.39e6);\n\n  final double mass;\n  final double radius;\n\n  const Planet(this.mass, this.radius);\n\n  double get gravity => 6.674e-11 * mass / (radius * radius);\n}\n\nvoid main() {\n  print(Planet.earth.gravity.toStringAsFixed(2)); // 9.82\n  print(Planet.values.map((p) => p.name).toList());\n}', level: QuestionLevel.intermediate, category: 'OOP'),
    InterviewQuestion(id: 'd23', question: 'What is the difference between synchronized and asynchronous operations in Dart?', answer: 'Dart is single-threaded but uses an event loop for async. Synchronous code blocks the event loop. Async code (async/await, Futures, Streams) schedules work on the event loop. Heavy CPU work should use Isolates. The microtask queue (scheduleMicrotask) runs before the event queue.', codeExample: '// Event loop order: sync > microtask > event\nvoid main() {\n  print("1: sync");\n\n  Future(() => print("4: event queue"));\n  Future.microtask(() => print("2: microtask"));\n  Future.value(42).then((_) => print("3: microtask (then)"));\n\n  print("5: sync again");\n}\n// Output: 1, 5, 2, 3, 4', level: QuestionLevel.advanced, category: 'Async'),
    InterviewQuestion(id: 'd24', question: 'What is the typedef keyword in Dart?', answer: 'typedef creates an alias for a function type or any type. Makes code more readable. Function typedefs are commonly used for callbacks and higher-order functions.', codeExample: '// Function typedef\ntypedef StringTransform = String Function(String);\ntypedef IntCallback = void Function(int);\n\nString applyTransform(String input, StringTransform fn) => fn(input);\n\nvoid main() {\n  final result = applyTransform("hello", (s) => s.toUpperCase());\n  print(result); // HELLO\n\n  // Type alias for complex types\n  typedef UserMap = Map<String, List<String>>;\n  final UserMap permissions = {\n    "admin": ["read", "write", "delete"],\n    "user": ["read"],\n  };\n}', level: QuestionLevel.intermediate, category: 'Functions'),
    InterviewQuestion(id: 'd25', question: 'How does Dart handle error handling?', answer: 'Dart uses try/catch/finally for synchronous errors. on catches specific types. rethrow re-throws the caught exception. async errors propagate through Futures. Use catchError or try/await/catch for async error handling.', codeExample: 'void main() async {\n  // Sync error handling\n  try {\n    int result = int.parse("not a number");\n    print(result);\n  } on FormatException catch (e) {\n    print("Format error: \${e.message}");\n  } on RangeError catch (e, stackTrace) {\n    print("Range error: \$e");\n    print(stackTrace);\n  } catch (e) {\n    print("Unknown error: \$e");\n  } finally {\n    print("Always runs");\n  }\n\n  // Async error handling\n  try {\n    final data = await fetchData();\n  } catch (e) {\n    print("Async error: \$e");\n  }\n\n  // Custom exception\n  // throw ValidationException("Invalid input");\n}', level: QuestionLevel.beginner, category: 'Error Handling'),
    InterviewQuestion(id: 'd26', question: 'What is the difference between compile-time and runtime in Dart?', answer: 'Dart can compile AOT (Ahead-of-Time) for production (native binary, faster startup) or JIT (Just-in-Time) for development (hot reload, faster iteration). const values are resolved at compile-time. Dart2js compiles to JavaScript for web.', level: QuestionLevel.intermediate, category: 'Compilation'),
    InterviewQuestion(id: 'd27', question: 'What are Collection if and Collection for in Dart?', answer: 'Collection if and collection for allow conditional and looping logic inside collection literals. Makes building dynamic lists/sets/maps more concise.', codeExample: 'bool isAdmin = true;\nString? optionalValue = "hello";\n\nfinal features = [\n  "basic",\n  if (isAdmin) "admin-panel",     // conditional inclusion\n  if (optionalValue != null) optionalValue, // null check\n];\n// ["basic", "admin-panel", "hello"]\n\n// Collection for\nfinal squares = [for (int i = 1; i <= 5; i++) i * i];\n// [1, 4, 9, 16, 25]\n\n// Combined\nfinal filtered = [\n  for (var i in [1, 2, 3, 4, 5])\n    if (i.isEven) i * 2,\n];\n// [4, 8]', level: QuestionLevel.beginner, category: 'Collections'),
    InterviewQuestion(id: 'd28', question: 'What are sound null safety and unsound null safety?', answer: 'Sound null safety means the analyzer and compiler guarantee null-safety throughout the program. Unsound mode mixes null-safe and legacy non-null-safe code (opt-out). Flutter 3.0+ uses sound null safety by default. Unsound safety can be enabled via --no-sound-null-safety for legacy migration purposes.', level: QuestionLevel.advanced, category: 'Null Safety'),
    InterviewQuestion(id: 'd29', question: 'How does inheritance work in Dart?', answer: 'Dart supports single inheritance with extends. Use super to call parent methods/constructors. Override methods with @override annotation. Abstract classes enforce method implementation in subclasses.', codeExample: 'class Animal {\n  final String name;\n  Animal(this.name);\n  void sound() => print("...");\n  @override\n  String toString() => "Animal(\$name)";\n}\n\nclass Dog extends Animal {\n  final String breed;\n  Dog(super.name, this.breed);\n\n  @override\n  void sound() {\n    super.sound(); // call parent\n    print("\$name barks!");\n  }\n}\n\nclass GoldenRetriever extends Dog {\n  GoldenRetriever(super.name) : super("Golden Retriever");\n}', level: QuestionLevel.beginner, category: 'OOP'),
    InterviewQuestion(id: 'd30', question: 'What are Dart metadata annotations?', answer: 'Metadata annotations start with @ and provide additional information about code. Built-in: @override, @deprecated, @pragma. Custom annotations are const classes. Used by code generators (build_runner), analyzers, and frameworks like Hive and Freezed.', codeExample: 'class Todo {\n  final String who;\n  final String what;\n  const Todo(this.who, this.what);\n}\n\nclass ApiService {\n  @Todo("John", "Add authentication")\n  @deprecated\n  void oldMethod() {}\n\n  @override\n  String toString() => "ApiService";\n}\n\n// Hive type adapter example\n@HiveType(typeId: 0)\nclass User extends HiveObject {\n  @HiveField(0)\n  late String name;\n  @HiveField(1)\n  late int age;\n}', level: QuestionLevel.intermediate, category: 'Metadata'),
  ];

  List<InterviewQuestion> get filteredQuestions {
    final all = selectedLevel.value == null
        ? allQuestions
        : allQuestions.where((q) => q.level == selectedLevel.value).toList();
    if (visibleCount.value >= all.length) return all;
    return all.sublist(0, visibleCount.value);
  }

  int get totalFilteredCount {
    if (selectedLevel.value == null) return allQuestions.length;
    return allQuestions.where((q) => q.level == selectedLevel.value).length;
  }

  bool get hasMore => visibleCount.value < totalFilteredCount;

  void loadMore() => visibleCount.value =
      (visibleCount.value + 10).clamp(0, totalFilteredCount);

  void toggleExpand(int index) {
    if (expandedIndex.value == index) {
      expandedIndex.value = -1;
    } else {
      expandedIndex.value = index;
    }
  }

  void filterByLevel(QuestionLevel? level) {
    selectedLevel.value = level;
    expandedIndex.value = -1;
    visibleCount.value = 10;
  }

  @override
  void onInit() async {
    scrollController = ScrollController()
      ..addListener(() {
        showBackToTopButton = scrollController.offset >= 400;
        update();
      });
    Get.find<SideMenuController>().selectPage(
      parent: SideNavBarParentEnum.interviewPrep,
      child: SideNavBarChildEnum.dartInterviewQA,
    );
    Get.find<AppBarController>().appBarTitle = SK.dartInterviewQA;
    update();
    super.onInit();
  }

  void scrollToTop() => scrollController.animateTo(0,
      duration: const Duration(seconds: 1), curve: Curves.linear);

  @override
  void dispose() {
    scrollController.dispose();
    super.dispose();
  }
}
