import 'package:dart_programing/app/views/enum/side_menu_enum.dart';
import 'package:dart_programing/app/views/side_menu/side_menu_controller.dart';
import 'package:dart_programing/modules/home/controllers/app_bar_controller.dart';
import 'package:dart_programing/modules/interview_prep/models/interview_question.dart';
import 'package:dart_programing/utils/constants/strings/string_keys.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class FlutterQAController extends GetxController {
  bool showBackToTopButton = false;
  late ScrollController scrollController;

  var selectedLevel = Rx<QuestionLevel?>(null);
  var expandedIndex = RxInt(-1);

  List<InterviewQuestion> allQuestions = [
    InterviewQuestion(id: 'f1', question: 'What is the difference between StatelessWidget and StatefulWidget?', answer: 'StatelessWidget is immutable — it builds once and only rebuilds when its parent passes new configuration. StatefulWidget has a mutable State object and can call setState() to trigger rebuilds. Use StatelessWidget for static content, StatefulWidget when the UI needs to change based on user interaction or data changes.', codeExample: '// StatelessWidget\nclass Label extends StatelessWidget {\n  final String text;\n  const Label({super.key, required this.text});\n  @override\n  Widget build(BuildContext context) => Text(text);\n}\n\n// StatefulWidget\nclass Counter extends StatefulWidget {\n  const Counter({super.key});\n  @override\n  State<Counter> createState() => _CounterState();\n}\nclass _CounterState extends State<Counter> {\n  int _count = 0;\n  @override\n  Widget build(BuildContext context) => TextButton(\n    onPressed: () => setState(() => _count++),\n    child: Text("Count: \$_count"),\n  );\n}', level: QuestionLevel.beginner, category: 'Widgets'),
    InterviewQuestion(id: 'f2', question: 'What is BuildContext in Flutter?', answer: 'BuildContext is a handle to the location of a widget in the widget tree. It provides access to the widget tree above it (Theme.of, MediaQuery.of, Navigator.of). Every build() method receives a BuildContext. Avoid storing BuildContext across async gaps — check if mounted first.', codeExample: 'Widget build(BuildContext context) {\n  // Access theme\n  final theme = Theme.of(context);\n  final color = theme.colorScheme.primary;\n\n  // Access media query\n  final size = MediaQuery.of(context).size;\n  final isDark = MediaQuery.platformBrightnessOf(context) == Brightness.dark;\n\n  // Navigate (avoid across async gaps)\n  return ElevatedButton(\n    onPressed: () async {\n      await Future.delayed(Duration(seconds: 1));\n      if (!context.mounted) return; // check mounted!\n      Navigator.push(context, MaterialPageRoute(builder: (_) => NextPage()));\n    },\n    child: Text("Go"),\n  );\n}', level: QuestionLevel.intermediate, category: 'Widgets'),
    InterviewQuestion(id: 'f3', question: 'What is the widget lifecycle in Flutter?', answer: 'StatefulWidget lifecycle: createState() → initState() → didChangeDependencies() → build() → didUpdateWidget() → setState() → build() → deactivate() → dispose(). initState: one-time setup. didChangeDependencies: InheritedWidget changes. didUpdateWidget: parent rebuilds with new config. dispose: cleanup controllers/subscriptions.', codeExample: 'class _MyWidgetState extends State<MyWidget> {\n  late AnimationController _ctrl;\n  late StreamSubscription _sub;\n\n  @override\n  void initState() {\n    super.initState(); // always call super first\n    _ctrl = AnimationController(vsync: this, duration: Duration(seconds: 1));\n    _sub = Stream.periodic(Duration(seconds: 1)).listen((_) => update());\n  }\n\n  @override\n  void didChangeDependencies() {\n    super.didChangeDependencies();\n    // Safe to use context here (e.g., read theme)\n  }\n\n  @override\n  void dispose() {\n    _ctrl.dispose(); // always dispose!\n    _sub.cancel();\n    super.dispose(); // always call super last\n  }\n}', level: QuestionLevel.intermediate, category: 'Widgets'),
    InterviewQuestion(id: 'f4', question: 'What are Keys in Flutter and when should you use them?', answer: 'Keys help Flutter identify widgets when the widget tree changes. Without keys, Flutter may reuse incorrect State objects when reordering or removing items. Use: ValueKey for unique identifiers, ObjectKey for object-based identity, UniqueKey for always-unique key. LocalKey (ValueKey, ObjectKey) for widgets in the same level, GlobalKey for accessing widget across the tree.', codeExample: 'ListView(\n  children: items.map((item) =>\n    // Without key: state may be reused incorrectly on reorder\n    ListTile(key: ValueKey(item.id), title: Text(item.name)),\n  ).toList(),\n)\n\n// GlobalKey — access state from outside\nfinal formKey = GlobalKey<FormState>();\nForm(key: formKey, child: ...)\nif (formKey.currentState!.validate()) { ... }\n\n// UniqueKey — always creates a new widget (resets state)\nAnimatedSwitcher(\n  child: SomeWidget(key: UniqueKey()), // force recreate\n)', level: QuestionLevel.intermediate, category: 'Widgets'),
    InterviewQuestion(id: 'f5', question: 'What is the difference between hot reload and hot restart in Flutter?', answer: 'Hot Reload: injects updated code into the running Dart VM, preserves app state, widget tree is rebuilt. Fast (~1 second). Does not re-run main() or initState(). Hot Restart: fully restarts the app, loses state, re-runs main(). Full Restart: stops and restarts the app from scratch, including native code changes.', level: QuestionLevel.beginner, category: 'Development'),
    InterviewQuestion(id: 'f6', question: 'How does Flutter render widgets?', answer: 'Flutter has three trees: Widget tree (immutable declarations), Element tree (mutable instances that bridge widget and render), and RenderObject tree (actual layout and painting). Flutter uses Skia/Impeller to paint directly to the canvas — no native widgets. This enables pixel-perfect rendering across platforms.', level: QuestionLevel.advanced, category: 'Architecture'),
    InterviewQuestion(id: 'f7', question: 'What are InheritedWidgets in Flutter?', answer: 'InheritedWidget is the foundation for propagating data down the widget tree efficiently. Widgets access it via context.dependOnInheritedWidgetOfExactType(). Only widgets that depend on it rebuild when it changes. Provider, Theme, MediaQuery, and Navigator all use InheritedWidget internally.', codeExample: 'class AppState extends InheritedWidget {\n  final String username;\n  final int cartCount;\n\n  const AppState({\n    required this.username,\n    required this.cartCount,\n    required super.child,\n  });\n\n  static AppState of(BuildContext context) =>\n      context.dependOnInheritedWidgetOfExactType<AppState>()!;\n\n  @override\n  bool updateShouldNotify(AppState oldWidget) =>\n      oldWidget.username != username || oldWidget.cartCount != cartCount;\n}', level: QuestionLevel.advanced, category: 'State Management'),
    InterviewQuestion(id: 'f8', question: 'What is const in Flutter and how does it improve performance?', answer: 'const widgets are created at compile-time and reused across rebuilds — the same instance is returned. This avoids unnecessary widget instantiation and rebuild. Apply const to widgets, constructors, and literals wherever possible. The Flutter linter (prefer_const_constructors) will suggest this.', codeExample: '// Without const — new instance every rebuild\nColumn(children: [\n  Text("Hello"),\n  Icon(Icons.star),\n])\n\n// With const — same instance reused, no rebuild\nconst Column(children: [\n  Text("Hello"),\n  Icon(Icons.star),\n])\n\n// Partial const\nColumn(children: [\n  const Text("Static text"), // this const subtree never rebuilds\n  Text(dynamicText),          // this rebuilds on change\n])', level: QuestionLevel.beginner, category: 'Performance'),
    InterviewQuestion(id: 'f9', question: 'What is RepaintBoundary and when should you use it?', answer: 'RepaintBoundary creates a separate layer for its subtree, preventing it from being repainted when other parts of the UI change. Use it around complex widgets that change independently (e.g., a video player, a frequently updating chart, or an expensive custom painter).', codeExample: '// Without RepaintBoundary:\n// If anything in the scaffold rebuilds, the expensive chart rebuilds too\n\n// With RepaintBoundary:\nColumn(children: [\n  // This header rebuilding won\'t cause chart to repaint\n  Text("Dynamic header: \${counter}"),\n\n  RepaintBoundary(\n    child: ExpensiveChart(data: staticData), // isolated\n  ),\n])', level: QuestionLevel.advanced, category: 'Performance'),
    InterviewQuestion(id: 'f10', question: 'What is the difference between Navigator.push and Navigator.pushReplacement?', answer: 'push adds a route to the stack (back button returns to previous). pushReplacement replaces the current route (back returns to the route before the replaced one). pushAndRemoveUntil removes all routes until a predicate matches. Use pushReplacement for login→home flow to prevent back navigation to login.', level: QuestionLevel.beginner, category: 'Navigation'),
    InterviewQuestion(id: 'f11', question: 'What is GoRouter and why use it over Navigator?', answer: 'GoRouter is the official declarative routing package for Flutter. Advantages: URL-based routing for web and deep linking, type-safe params, redirect guards for authentication, ShellRoute for persistent navigation, declarative route configuration, better for complex navigation hierarchies.', level: QuestionLevel.intermediate, category: 'Navigation'),
    InterviewQuestion(id: 'f12', question: 'Explain the difference between Expanded and Flexible widgets.', answer: 'Both work inside Row/Column. Expanded forces the child to fill all remaining space (equivalent to Flexible with FlexFit.tight). Flexible allows the child to be smaller than the available space (FlexFit.loose). Use Expanded when you want the widget to fill; Flexible when you want it to use only what it needs.', codeExample: 'Row(children: [\n  // Expanded: fills remaining space — no smaller\n  Expanded(\n    flex: 2,\n    child: Container(color: Colors.red, height: 50),\n  ),\n  // Flexible: can be smaller than its allocated space\n  Flexible(\n    flex: 1,\n    child: Text("I take what I need"), // may be smaller\n  ),\n])', level: QuestionLevel.beginner, category: 'Layout'),
    InterviewQuestion(id: 'f13', question: 'What is a LayoutBuilder and when should you use it?', answer: 'LayoutBuilder gives you the parent widget\'s constraints so you can build responsive layouts. Use it when you need to make layout decisions based on available space rather than screen size. Better than MediaQuery for component-level responsiveness.', codeExample: 'LayoutBuilder(\n  builder: (context, constraints) {\n    if (constraints.maxWidth > 600) {\n      return DesktopLayout();\n    } else {\n      return MobileLayout();\n    }\n  },\n)', level: QuestionLevel.intermediate, category: 'Layout'),
    InterviewQuestion(id: 'f14', question: 'What are platform channels in Flutter?', answer: 'Platform channels allow Flutter to communicate with native iOS/Android code. MethodChannel: call native methods from Dart (bidirectional). EventChannel: stream events from native to Dart. BasicMessageChannel: send/receive basic messages. Used for: accessing hardware sensors, native SDKs, platform-specific features.', codeExample: '// Dart side\nconst platform = MethodChannel("com.example/battery");\nFuture<int> getBatteryLevel() async {\n  try {\n    final level = await platform.invokeMethod<int>("getBatteryLevel");\n    return level ?? -1;\n  } on PlatformException catch (e) {\n    print("Failed: \${e.message}");\n    return -1;\n  }\n}\n\n// Android Kotlin side\nmethodChannel.setMethodCallHandler { call, result ->\n  if (call.method == "getBatteryLevel") {\n    val batteryLevel = getBatteryLevel()\n    result.success(batteryLevel)\n  }\n}', level: QuestionLevel.advanced, category: 'Native'),
    InterviewQuestion(id: 'f15', question: 'What is setState() and when should you use it?', answer: 'setState() notifies Flutter that the state has changed and the widget should rebuild. Only use it in StatefulWidget. The callback passed to setState should be synchronous and only modify state variables. setState() is suitable for local state within a single widget — use state management solutions for shared state.', codeExample: '// Correct usage\nvoid _incrementCounter() {\n  setState(() {\n    _counter++; // synchronous state modification\n  });\n}\n\n// Wrong: async inside setState\nvoid _wrongUsage() {\n  setState(() async {\n    _data = await fetchData(); // DON\'T do this\n  });\n}\n\n// Correct async pattern\nFuture<void> _loadData() async {\n  final data = await fetchData();\n  if (mounted) { // check mounted after async gap\n    setState(() => _data = data);\n  }\n}', level: QuestionLevel.beginner, category: 'State Management'),
    InterviewQuestion(id: 'f16', question: 'What is a StreamBuilder and when should you use it?', answer: 'StreamBuilder rebuilds its child whenever a new event is emitted from a Stream. It has ConnectionState (none, waiting, active, done) and AsyncSnapshot. Perfect for real-time data (Firebase, WebSockets, BLoC streams).', codeExample: 'StreamBuilder<List<Message>>(\n  stream: chatRepository.messagesStream,\n  builder: (context, snapshot) {\n    if (snapshot.connectionState == ConnectionState.waiting) {\n      return const CircularProgressIndicator();\n    }\n    if (snapshot.hasError) {\n      return Text("Error: \${snapshot.error}");\n    }\n    if (!snapshot.hasData || snapshot.data!.isEmpty) {\n      return const Text("No messages yet");\n    }\n    final messages = snapshot.data!;\n    return ListView.builder(\n      itemCount: messages.length,\n      itemBuilder: (_, i) => MessageTile(message: messages[i]),\n    );\n  },\n)', level: QuestionLevel.intermediate, category: 'Async UI'),
    InterviewQuestion(id: 'f17', question: 'What is FutureBuilder and when should you use it?', answer: 'FutureBuilder rebuilds based on the state of a Future. Returns a widget based on ConnectionState and snapshot data. Important: the Future passed should not be created directly in build() — create it in initState or a controller to prevent recreation on every rebuild.', codeExample: 'class UserPage extends StatefulWidget {\n  const UserPage({super.key});\n  @override\n  State<UserPage> createState() => _UserPageState();\n}\n\nclass _UserPageState extends State<UserPage> {\n  late Future<User> _userFuture;\n\n  @override\n  void initState() {\n    super.initState();\n    _userFuture = fetchUser(1); // create once!\n  }\n\n  @override\n  Widget build(BuildContext context) {\n    return FutureBuilder<User>(\n      future: _userFuture,\n      builder: (context, snapshot) => switch (snapshot.connectionState) {\n        ConnectionState.waiting => const CircularProgressIndicator(),\n        ConnectionState.done when snapshot.hasError =>\n            Text("Error: \${snapshot.error}"),\n        ConnectionState.done => Text("Hello \${snapshot.data!.name}"),\n        _ => const SizedBox.shrink(),\n      },\n    );\n  }\n}', level: QuestionLevel.intermediate, category: 'Async UI'),
    InterviewQuestion(id: 'f18', question: 'How do you handle deep linking in Flutter?', answer: 'Deep linking allows URLs to open specific pages in your app. GoRouter handles deep linking automatically with URL-based routing. Requires: app_links package (or similar), configuring intent filters (Android) and associated domains (iOS), and defining matching routes in GoRouter.', level: QuestionLevel.advanced, category: 'Navigation'),
    InterviewQuestion(id: 'f19', question: 'What are the different types of state in Flutter?', answer: 'Ephemeral state (local state): only needed within a widget, use StatefulWidget + setState. App state (shared state): needed by multiple widgets, use state management. Server state: data from backend, use FutureProvider/TanStack Query patterns. URL state: navigation state, use GoRouter.', level: QuestionLevel.intermediate, category: 'State Management'),
    InterviewQuestion(id: 'f20', question: 'What is the difference between SingleChildScrollView and ListView?', answer: 'SingleChildScrollView scrolls a single child — good for forms and content that occasionally overflows. ListView is optimized for scrolling many items. ListView.builder is lazy (only builds visible items). Use SingleChildScrollView for forms, ListView for lists.', level: QuestionLevel.beginner, category: 'Widgets'),
    InterviewQuestion(id: 'f21', question: 'What is a CustomPainter in Flutter?', answer: 'CustomPainter allows drawing custom shapes, lines, and curves using a Canvas. Override paint() to draw and shouldRepaint() to control when to repaint. Use RepaintBoundary to isolate repaints. Good for charts, graphs, custom gauges, and unique UI elements.', codeExample: 'class CirclePainter extends CustomPainter {\n  final Color color;\n  final double radius;\n\n  CirclePainter({required this.color, required this.radius});\n\n  @override\n  void paint(Canvas canvas, Size size) {\n    final paint = Paint()\n      ..color = color\n      ..style = PaintingStyle.fill;\n    canvas.drawCircle(\n      Offset(size.width / 2, size.height / 2),\n      radius,\n      paint,\n    );\n  }\n\n  @override\n  bool shouldRepaint(CirclePainter old) =>\n      old.color != color || old.radius != radius;\n}\n\nCustomPaint(\n  size: const Size(200, 200),\n  painter: CirclePainter(color: Colors.blue, radius: 80),\n)', level: QuestionLevel.advanced, category: 'Custom UI'),
    InterviewQuestion(id: 'f22', question: 'What are Slivers in Flutter?', answer: 'Slivers are scrollable pieces of the UI used with CustomScrollView. They provide fine-grained control over scrolling behavior. SliverAppBar collapses on scroll. SliverList and SliverGrid for lists and grids. SliverToBoxAdapter wraps non-sliver widgets. SliverFillRemaining fills remaining scroll space.', codeExample: 'CustomScrollView(\n  slivers: [\n    const SliverAppBar(\n      title: Text("My App"),\n      floating: true,\n      pinned: true,\n      expandedHeight: 200,\n      flexibleSpace: FlexibleSpaceBar(\n        background: Image.network("url", fit: BoxFit.cover),\n      ),\n    ),\n    SliverList(\n      delegate: SliverChildBuilderDelegate(\n        (context, index) => ListTile(title: Text("Item \$index")),\n        childCount: 50,\n      ),\n    ),\n    const SliverFillRemaining(\n      child: Center(child: Text("End of list")),\n    ),\n  ],\n)', level: QuestionLevel.advanced, category: 'Widgets'),
    InterviewQuestion(id: 'f23', question: 'What is Semantics in Flutter and why is it important?', answer: 'Semantics describe the meaning of widgets for accessibility tools (screen readers, TalkBack, VoiceOver). Flutter auto-generates semantics for most widgets, but you can customize with the Semantics widget. Add semantic labels, hints, and actions for better accessibility. Test with the Accessibility Inspector in DevTools.', level: QuestionLevel.intermediate, category: 'Accessibility'),
    InterviewQuestion(id: 'f24', question: 'What are the best practices for optimizing Flutter app performance?', answer: '1. Use const constructors. 2. Use ListView.builder for long lists. 3. Add RepaintBoundary around complex, independently-updating widgets. 4. Avoid blocking the main thread — use Isolates for CPU-heavy work. 5. Cache images properly (cached_network_image). 6. Use build_filter/selector for minimal rebuilds. 7. Lazy-load content. 8. Profile with Flutter DevTools.', level: QuestionLevel.advanced, category: 'Performance'),
    InterviewQuestion(id: 'f25', question: 'What is the difference between pushNamed and push in Flutter Navigator?', answer: 'pushNamed uses route names registered in MaterialApp routes map. push takes a Route object directly. pushNamed is more maintainable for named routing but lacks type safety. For type-safe navigation with deep linking, use GoRouter instead.', level: QuestionLevel.beginner, category: 'Navigation'),
    InterviewQuestion(id: 'f26', question: 'What is image caching in Flutter and how do you implement it?', answer: 'Flutter\'s Image.network caches images in memory but not persistently. Use cached_network_image package for persistent disk caching with placeholder and error handling. ImageCache class controls the memory cache size (default 1000 images or 100 MB).', codeExample: '// cached_network_image\nCachedNetworkImage(\n  imageUrl: "https://example.com/image.jpg",\n  placeholder: (context, url) => const CircularProgressIndicator(),\n  errorWidget: (context, url, error) => const Icon(Icons.error),\n  fit: BoxFit.cover,\n  width: 200,\n  height: 200,\n)\n\n// Configure cache size\nPaintingBinding.instance.imageCache.maximumSize = 100;\nPaintingBinding.instance.imageCache.maximumSizeBytes = 50 * 1024 * 1024;', level: QuestionLevel.intermediate, category: 'Performance'),
    InterviewQuestion(id: 'f27', question: 'What is the mounted property in Flutter?', answer: 'mounted is a bool on State that is true when the widget is in the widget tree and false after dispose(). Always check mounted before calling setState() after an async operation, to prevent "setState() called after dispose()" errors.', codeExample: 'Future<void> loadData() async {\n  final data = await fetchDataFromApi();\n\n  // Without mounted check — may crash!\n  setState(() => _data = data); // DANGEROUS after async\n\n  // With mounted check — safe\n  if (mounted) {\n    setState(() => _data = data);\n  }\n\n  // Also check in BuildContext\n  if (!context.mounted) return;\n  Navigator.push(context, ...);\n}', level: QuestionLevel.intermediate, category: 'Widgets'),
    InterviewQuestion(id: 'f28', question: 'What is tree shaking in Flutter?', answer: 'Tree shaking removes unused code from the final binary during compilation. Flutter\'s release builds automatically tree-shake Dart code. Icons are tree-shaken if you use the --no-tree-shake-icons flag carefully. Use --analyze-size to inspect what is included in your app binary.', level: QuestionLevel.advanced, category: 'Build'),
    InterviewQuestion(id: 'f29', question: 'What is the difference between Container and SizedBox?', answer: 'Container is heavyweight — adds layer, clipping, and painting if properties are set. SizedBox is lightweight — only constrains size with no painting overhead. Prefer SizedBox for fixed sizes and as spacers. Prefer Container when you need decoration (color, border, shadow, borderRadius).', codeExample: '// SizedBox — simple size constraint or spacer\nSizedBox(width: 16)        // horizontal spacer\nSizedBox(height: 8)         // vertical spacer\nSizedBox(width: 100, height: 100, child: MyWidget())\n\n// Container — when you need decoration\nContainer(\n  width: 100,\n  height: 100,\n  decoration: BoxDecoration(\n    color: Colors.blue,\n    borderRadius: BorderRadius.circular(8),\n    boxShadow: [BoxShadow(color: Colors.black26, blurRadius: 4)],\n  ),\n  child: const Icon(Icons.star),\n)', level: QuestionLevel.beginner, category: 'Widgets'),
    InterviewQuestion(id: 'f30', question: 'What is gesture detection in Flutter?', answer: 'GestureDetector wraps a widget and detects gestures: onTap, onDoubleTap, onLongPress, onPanUpdate, onScaleUpdate, etc. InkWell adds Material ripple effect. Listener provides raw pointer events. GestureDetector.behavior controls how it responds to touch areas.', codeExample: 'GestureDetector(\n  onTap: () => print("Tapped!"),\n  onDoubleTap: () => print("Double tapped!"),\n  onLongPress: () => print("Long pressed!"),\n  onPanUpdate: (details) {\n    // drag: details.delta.dx, details.delta.dy\n  },\n  onScaleUpdate: (details) {\n    // pinch: details.scale, details.rotation\n  },\n  child: Container(\n    width: 100,\n    height: 100,\n    color: Colors.blue,\n  ),\n)\n\n// InkWell for Material ripple\nInkWell(\n  onTap: () {},\n  borderRadius: BorderRadius.circular(8),\n  child: Padding(\n    padding: EdgeInsets.all(16),\n    child: Text("Click me"),\n  ),\n)', level: QuestionLevel.beginner, category: 'Interaction'),
  ];

  List<InterviewQuestion> get filteredQuestions {
    if (selectedLevel.value == null) return allQuestions;
    return allQuestions.where((q) => q.level == selectedLevel.value).toList();
  }

  void toggleExpand(int index) {
    if (expandedIndex.value == index) {
      expandedIndex.value = -1;
    } else {
      expandedIndex.value = index;
    }
  }

  void filterByLevel(QuestionLevel? level) {
    selectedLevel.value = level;
    expandedIndex.value = -1;
  }

  @override
  void onInit() async {
    scrollController = ScrollController()
      ..addListener(() {
        showBackToTopButton = scrollController.offset >= 400;
        update();
      });
    Get.find<SideMenuController>().selectPage(
      parent: SideNavBarParentEnum.interviewPrep,
      child: SideNavBarChildEnum.flutterInterviewQA,
    );
    Get.find<AppBarController>().appBarTitle = SK.flutterInterviewQA;
    update();
    super.onInit();
  }

  void scrollToTop() => scrollController.animateTo(0,
      duration: const Duration(seconds: 1), curve: Curves.linear);

  @override
  void dispose() {
    scrollController.dispose();
    super.dispose();
  }
}
